### ISSUE TITLE
Sending Event counts to librato

### ISSUE THREAD

**Issue by oddurmagg** [rcrowley/go-metrics#102]
Would it make sense to be able to send counter deltas to librarto, so that in Librato we can use server-side-aggregation and use the distributed event counting: http://support.metrics.librato.com/knowledgebase/articles/213775-what-is-service-side-aggregation-ssa

That would require the Reporter to report counters as gauges in librato and remember the last value send for that counter and subtract that from the value being reported.

**Comment by mihasya** [comment]
@oddurmagg I think what you're trying to do can be accomplished without SSA. If you send Librato counter data from multiple sources, you can just sum those up and take their derivative in aggregate using [composite metrics](http://support.metrics.librato.com/knowledgebase/articles/337431-composite-metrics-language-specification).

Closing one way or another, because [of this policy](https://github.com/rcrowley/go-metrics/issues/105#issuecomment-72514186). If this is still an issue, please do reopen it once I've split the Librato client into its own little  repo.
