### ISSUE TITLE
Stopping metrics reporters

### ISSUE THREAD

**Issue by imkira** [rcrowley/go-metrics#110]
Is there any reason why there is no official way of stopping a reporter once you have called its reporting function?

Example (Log reporter):

https://github.com/rcrowley/go-metrics/blob/master/log.go#L10

In order to be more test-friendly and to be able to gracefully stop metric reporting it would be cool to have such feature. I could try working on a PR for this. What do you think?

**Comment by tsenart** [comment]
+1

On Tuesday, March 24, 2015, Mário Freitas <notifications@github.com> wrote:

> Is there any reason why there is no official way of stopping a reporter
> once you have called its reporting function?
>
> Example (Log reporter):
>
> https://github.com/rcrowley/go-metrics/blob/master/log.go#L10
>
> In order to be more test-friendly and to be able to gracefully stop metric
> reporting it would be cool to have such feature. I could try working on a
> PR for this. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcrowley/go-metrics/issues/110>.
>


-- 
Sent from Gmail Mobile

**Comment by mihasya** [comment]
I'd happily review a PR, but I'm not 100% sure it's worth the effort - reporting is usually not a critical component of the application, and all resources associated with it get released when the process exits. It would have to be an extremely clean, low impact patch where existing implementations such as the logger could remain very simple.

I think @rcrowley originally avoided introducing a special reporter interface because they all have subtly different needs. It may make even less sense as I start to enforce [this policy](https://github.com/rcrowley/go-metrics/issues/105#issuecomment-72514186)

**Comment by mihasya** [comment]
Closing until there's a PR to discuss. Thanks!
