### ISSUE TITLE
Reset collected metrics after exporting

### ISSUE THREAD

**Issue by FZambia** [rcrowley/go-metrics#120]
Hello! Could you point me in a right direction please.

The only thing I need is to export metrics into Graphite (only 3 types actually - counters, gauges and timers).

I looked through code and examples and it seems that counters and timers keep all previously collected data and not clearing automatically after exporting. I can imagine that this is the only way to prevent collapse when using multiple exporters. But what is the usage of such counters and timers - both just provide sum of all events happened since application start while we just need an amount of events (or timer values) since last exporting. I.e how many requests we got in a minute, how many times function was called etc. In case of timers - what is the average response time in last minute etc.

I see `Clear()` method for `Counter` type so I would able to clear it manually. But `Timer` has no `Clear()` method.

So what's the decision? Is this library not designed for tasks I described above?

**Comment by mihasya** [comment]
Hey there! Counters are monotonically increasing, unless reset. Timers use a histogram with a decay function under the hood, so you can think of it as a moving window - the output will be biased towards the most recent samples, with older samples dropping out of the picture entirely over time. You can see the [`NewTimer` constructor](https://github.com/rcrowley/go-metrics/blob/master/timer.go#L61-L69) to see the defaults and follow the thread from there to see what else is possible.

Hope this helps!

**Comment by mihasya** [comment]
Sorry, I didn't answer your question directly. You can see that the other variable the `Timer` depends on is a meter - that actually uses an exponentially weighted moving average ("EWMA") to achieve the same end.  Your use case will work just fine, as the values provided by the `Timer` will reflect the most recent datapoints. You can plug in a different implementations of `Histogram` and `Meter`, and there are a few options and tuning knobs available for both.

We've been using the defaults in production at Opsmatic and they work just fine. Similar techniques used to calculate things like load in Linux and various timing metrics in services such as Apache.

**Comment by FZambia** [comment]
Thanks for your answer @mihasya - things are more clear now, I will try to experiment with timers, the thing I already noticed - if new time interval did not introduce new timer events - exported timer values remain the same:

```
package main

import (
	"github.com/rcrowley/go-metrics"
	"log"
	"os"
	"time"
)

const fanout = 10
const limit = 10

func main() {

	r := metrics.NewRegistry()

	t := metrics.NewTimer()
	r.Register("hooah", t)
	for i := 0; i < fanout; i++ {
		go func() {
			j := 0
			for {
				if j < limit {
					t.Time(func() { time.Sleep(300e6) })
				} else {
					break
					//t.Time(func() { time.Sleep(1e6) })
					//time.Sleep(299e6)
				}
				j++
			}
		}()
		go func() {
			k := 0
			for {
				if k < limit {
					t.Time(func() { time.Sleep(400e6) })
				} else {
					break
					//t.Time(func() { time.Sleep(2e6) })
					//time.Sleep(398e6)
				}
				k++
			}
		}()
	}

	metrics.Log(r, 1e9, log.New(os.Stderr, "metrics: ", log.Lmicroseconds))
}
```

Also timer `max` value not updated at all when new timer events are much more fast (uncomment 4 lines in example above and remove `break` statements).

**Comment by mihasya** [comment]
@FZambia these metrics are aggregates, so it makes sense that they don't move with every single data point. Think about what "max" is supposed to mean - it's the highest value seen, right? Of course, in webops "absolute" values "since last restart" are not very useful, which is why capped samples are employed.  Follow the code from [here](https://github.com/rcrowley/go-metrics/blob/d4f1d6222627a1f769d0f2787badd4dad9abcfd2/timer.go#L65-L69) to [here](https://github.com/rcrowley/go-metrics/blob/d4f1d6222627a1f769d0f2787badd4dad9abcfd2/histogram.go#L29-L35) and [here](https://github.com/rcrowley/go-metrics/blob/d4f1d6222627a1f769d0f2787badd4dad9abcfd2/sample.go#L47-L61) - you will see that the `Sample` being used uses a "reservoir" of 1028 data points. I simply don't think you're pushing in enough data points to cause the previous "max" value to be pushed out of the "reservoir."

If you look at the comment above `NewTimer`, you'll see the defaults were pulled from Unix load averages - those are updated quite frequently.

Hope this helps. I'm closing this issue as I start the trek to "inbox 0" on this repo. Cheers.

**Comment by FZambia** [comment]
Thanks a lot, this information will definitely help. I did not mean that this behaviour is somewhat buggy - just wanted to understand how to adapt it to my needs, now I see that I have not noticed lots of internal stuff.
